# Generated by Django 4.1 on 2022-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('post_id', models.IntegerField()),
                ('author', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('responses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommentResponse',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('comment_id', models.IntegerField()),
                ('author', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=2048)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
            ],
        ),
    ]
