# Generated by Django 4.1 on 2022-09-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
