# Generated by Django 4.1.2 on 2023-03-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_read_replynotification_commentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
