# Generated by Django 4.1 on 2022-09-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_delete_comment_delete_message_delete_post'),
        ('api', '0005_alter_comment_author_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentresponse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.user'),
        ),
    ]
