# Generated by Django 4.1 on 2022-09-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_commentresponse_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='commentresponse',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='user_id',
            new_name='user',
        ),
    ]
