# Generated by Django 4.1 on 2022-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_groupmembers_groupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
