# Generated by Django 4.1 on 2022-09-02 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_profilepictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
        migrations.RenameModel(
            old_name='ProfilePictures',
            new_name='ProfilePicture',
        ),
    ]
