# Generated by Django 4.1 on 2022-09-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_post_comments_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=32),
        ),
    ]
