# Generated by Django 4.1 on 2022-09-08 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_replylike_commentlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentResponse',
            new_name='Reply',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='post',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='replylike',
            name='post',
        ),
        migrations.AddField(
            model_name='replylike',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
