# Generated by Django 4.1 on 2022-08-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_comment_message_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
